version: '3.8'

services:
  soap-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3308
    ports:
      - 3308:3308
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_TCP_PORT: 3308
    container_name: soap-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3308"]
      interval: 10s
      timeout: 120s
      retries: 11

  soap:
    build: .
    depends_on:
      soap-database:
        condition: service_healthy
    ports:
      - 3003:3003
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - DB_HOST=soap-database
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=binotify-soap
      - DB_PORT=3308
      - PHP_CALLBACK_URL=http://host.docker.internal:3001/api/update_status.php
      - REST_API_URL=http://host.docker.internal:3002
      - MAIL_MODE=prod
      - MAIL_PASSWORD=
    container_name: soap-service